# Generated by Django 5.1 on 2024-08-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
