# Generated by Django 5.1 on 2024-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_remove_event_organizer_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='event',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
