# Generated by Django 5.1 on 2024-09-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
